language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8

before_script:
  - mv django/santropolFeast/santropolFeast/settings_test.py django/santropolFeast/santropolFeast/settings.py

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* django/santropolFeast/manage.py test member
  - pep8 --count --show-source --exclude=migrations django/santropolFeast/

after_success:
  - coveralls

after_failure:
  - coveralls
